Models/Classroom.cs
using System.ComponentModel.DataAnnotations;

namespace WDA_PE.Models;

public class Classroom
{
    [Key]
    public Guid ClassroomId { get; set; }
    [Required]
    [StringLength(5, ErrorMessage = "RoomNo cannot be longer than 5 characters.")]
    public string RoomNo { get; set; }
}

Models/ErrorViewModel.cs
namespace WDA_PE.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Exam.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WDA_PE.Models;

public class Exam
{
    [Key]
    public Guid ExamId { get; set; }
    [DataType(DataType.Date)] public DateTime DateTime { get; set; }
    public int Duration { get; set; }
    [ForeignKey("ClassroomId")] public Classroom Classroom { get; set; }
    [ForeignKey("FacultyId")] public Faculty Faculty { get; set; }
    [ForeignKey("SubjectId")] public Subject Subject { get; set; }
    
}

Models/Faculty.cs
using System.ComponentModel.DataAnnotations;

namespace WDA_PE.Models;

public class Faculty
{
    [Key] public Guid FacultyId { get; set; }

    [StringLength(50, ErrorMessage = "Name cannot be longer than 50 characters.")]
    public string Name { get; set; }
}

Models/Subject.cs
using System.ComponentModel.DataAnnotations;

namespace WDA_PE.Models;

public class Subject
{
    [Key]
    public Guid SubjectId { get; set; }
    [Required]
    [StringLength(50, ErrorMessage = "RoomNo cannot be longer than 50 characters.")]
    public string SubjectName { get; set; }
}

Controllers/ExamController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WDA_PE.Models;
using WDA_PE.Repositories;

namespace WDA_PE.Controllers;

public class ExamController : Controller
{
    private readonly AppDbContext _dbContext;
    private readonly IRepository<Exam> _examRepository;
    private readonly IRepository<Classroom> _classroomRepository;
    private readonly IRepository<Subject> _subjectRepository;
    private readonly IRepository<Faculty> _facultyRepository;

    public ExamController(AppDbContext dbContext,
        IRepository<Exam> examRepository,
        IRepository<Classroom> classroomRepository,
        IRepository<Subject> subjectRepository,
        IRepository<Faculty> facultyRepository)
    {
        _dbContext = dbContext;
        _examRepository = examRepository;
        _classroomRepository = classroomRepository;
        _subjectRepository = subjectRepository;
        _facultyRepository = facultyRepository;
    }

    public async Task<IActionResult> Index()
    {
        List<Exam> exams = await _examRepository.Get().ToListAsync();
        ViewBag.exams = exams;
        return View();
    }

    public async Task<IActionResult> Add()
    {
        List<Subject> subjects = await _subjectRepository.Get().ToListAsync();
        List<Classroom> classrooms = await _classroomRepository.Get().ToListAsync();
        List<Faculty> faculties = await _facultyRepository.Get().ToListAsync();
        ViewBag.subjects = subjects;
        ViewBag.classrooms = classrooms;
        ViewBag.faculties = faculties;
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Add(Exam exam, Guid subject, Guid classroom, Guid faculty)
    {
        exam.Classroom = await _classroomRepository.GetById(classroom);
        exam.Subject = await _subjectRepository.GetById(subject);
        exam.Faculty = await _facultyRepository.GetById(faculty);
        var res = await _examRepository.Create(exam);
        return RedirectToAction("Index");
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WDA_PE.Models;

namespace WDA_PE.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Exam/Add.cshtml
@model Exam
@{
    List<Subject> subjects = ViewBag.subjects;
    List<Classroom> classrooms = ViewBag.classrooms;
    List<Faculty> faculties = ViewBag.faculties;
}

<h1>Create New Exam</h1>
<form action="~/Exam/Add" method="post">
    <div class="form-group">
        <label>Exam Subject</label>
        <select name="Subject" class="form-control">
            @foreach (var s in subjects)
            {
                <option value=@s.SubjectId>@s.SubjectName</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label>Start Time</label>
        <input class="form-control" asp-for="DateTime"  asp-format="{0:yyyy-MM-ddTHH:mm}" name="DateTime" required="required" type="datetime-local"/>
    </div>
    <div class="form-group">
        <label>Exam Duration</label>
        <input class="form-control" name="Duration" required="required" type="number" min=0/>
    </div>
    <div class="form-group">
        <label>Class Room</label>
        <select name="Classroom" class="form-control">
            @foreach (var c in classrooms)
            {
                <option value=@c.ClassroomId>@c.RoomNo</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label>Exam Subject</label>
        <select name="Faculty" class="form-control">
            @foreach (var f in faculties)
            {
                <option value=@f.FacultyId>@f.Name</option>
            }
        </select>
    </div>
    <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
</form>

Views/Exam/Index.cshtml
@{
    List<Exam> exams = ViewBag.exams;
}

<table class="table">
    <thead>
    <th>Subject</th>
    <th>Start Time</th>
    <th>Exam Date</th>
    <th>Duration</th>
    <th>Class Room</th>
    <th>Faculty</th>
    <th>Status</th>
    </thead>
    <tbody>
    @foreach( var e in exams)
    {
        <tr>
            <td>@e.Subject.SubjectName</td>
            <td>@e.DateTime.ToShortTimeString()</td>
            <td>@e.DateTime.ToLongDateString()</td>
            <td>@e.Duration</td>
            <td>@e.Classroom.RoomNo</td>
            <td>@e.Faculty.Name</td>
            @if (e.DateTime.AddMinutes(e.Duration).CompareTo(DateTime.Now) < 0)
                {
                   <td> Done </td>
                }       
            @if (e.DateTime.AddMinutes(e.Duration).CompareTo(DateTime.Now) > 0 && e.DateTime.CompareTo(DateTime.Now) <=0)
                {
                   <td> On Going </td>
                }       
            @if (e.DateTime.CompareTo(DateTime.Now) > 0)
                {
                   <td> Up Coming </td>
                }
            </tr>
    }
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WDA_PE</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WDA_PE.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WDA_PE</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Exam" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Exam" asp-action="Add">Add</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - WDA_PE - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>